export const migrations = [
  {
    "name": "0000_useful_mathemanic.sql",
    "statements": [
      "CREATE TABLE \"alerts\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"site_id\" uuid NOT NULL,\n\t\"title\" text NOT NULL,\n\t\"message\" text NOT NULL,\n\t\"alert_type\" text NOT NULL,\n\t\"resolved\" boolean DEFAULT false NOT NULL,\n\t\"created_at\" timestamp DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"checks\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"url_id\" uuid NOT NULL,\n\t\"check_type\" text NOT NULL,\n\t\"status\" text NOT NULL,\n\t\"details\" jsonb NOT NULL,\n\t\"checked_at\" timestamp DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"sitemaps\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"site_id\" uuid NOT NULL,\n\t\"url\" text NOT NULL,\n\t\"status\" text DEFAULT 'pending' NOT NULL,\n\t\"last_sync_time\" timestamp,\n\t\"error_message\" text,\n\t\"created_at\" timestamp DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"sites\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"user_id\" text NOT NULL,\n\t\"domain\" text NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"verified\" boolean DEFAULT false NOT NULL,\n\t\"verification_token\" text NOT NULL,\n\t\"sitemap_url\" text,\n\t\"created_at\" timestamp DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"submissions\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"site_id\" uuid NOT NULL,\n\t\"loc\" text NOT NULL,\n\t\"engine\" text NOT NULL,\n\t\"status\" text NOT NULL,\n\t\"response_message\" text,\n\t\"created_at\" timestamp DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"urls\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"site_id\" uuid NOT NULL,\n\t\"loc\" text NOT NULL,\n\t\"priority\" text DEFAULT '0.5' NOT NULL,\n\t\"lastmod\" timestamp,\n\t\"changefreq\" text,\n\t\"indexing_status\" text DEFAULT 'unknown' NOT NULL,\n\t\"gsc_status\" text DEFAULT 'unknown' NOT NULL,\n\t\"http_status\" integer,\n\t\"last_checked_at\" timestamp,\n\t\"created_at\" timestamp DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"users\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"email\" text NOT NULL,\n\t\"billing_tier\" text DEFAULT 'free' NOT NULL,\n\t\"created_at\" timestamp DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp DEFAULT now() NOT NULL\n);",
      "ALTER TABLE \"alerts\" ADD CONSTRAINT \"alerts_site_id_sites_id_fk\" FOREIGN KEY (\"site_id\") REFERENCES \"public\".\"sites\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "ALTER TABLE \"checks\" ADD CONSTRAINT \"checks_url_id_urls_id_fk\" FOREIGN KEY (\"url_id\") REFERENCES \"public\".\"urls\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "ALTER TABLE \"sitemaps\" ADD CONSTRAINT \"sitemaps_site_id_sites_id_fk\" FOREIGN KEY (\"site_id\") REFERENCES \"public\".\"sites\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "ALTER TABLE \"sites\" ADD CONSTRAINT \"sites_user_id_users_id_fk\" FOREIGN KEY (\"user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "ALTER TABLE \"submissions\" ADD CONSTRAINT \"submissions_site_id_sites_id_fk\" FOREIGN KEY (\"site_id\") REFERENCES \"public\".\"sites\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "ALTER TABLE \"urls\" ADD CONSTRAINT \"urls_site_id_sites_id_fk\" FOREIGN KEY (\"site_id\") REFERENCES \"public\".\"sites\"(\"id\") ON DELETE cascade ON UPDATE no action;"
    ]
  },
  {
    "name": "0001_add_dashboard_indexes.sql",
    "statements": [
      "CREATE INDEX \"alerts_site_id_idx\" ON \"alerts\" USING btree (\"site_id\");",
      "CREATE INDEX \"alerts_site_resolved_created_idx\" ON \"alerts\" USING btree (\"site_id\",\"resolved\",\"created_at\");",
      "CREATE INDEX \"checks_url_id_idx\" ON \"checks\" USING btree (\"url_id\");",
      "CREATE INDEX \"checks_url_checked_idx\" ON \"checks\" USING btree (\"url_id\",\"checked_at\");",
      "CREATE INDEX \"sitemaps_site_id_idx\" ON \"sitemaps\" USING btree (\"site_id\");",
      "CREATE INDEX \"sitemaps_site_created_idx\" ON \"sitemaps\" USING btree (\"site_id\",\"created_at\");",
      "CREATE INDEX \"sites_user_id_idx\" ON \"sites\" USING btree (\"user_id\");",
      "CREATE UNIQUE INDEX \"sites_user_domain_unique_idx\" ON \"sites\" USING btree (\"user_id\",\"domain\");",
      "CREATE INDEX \"submissions_site_id_idx\" ON \"submissions\" USING btree (\"site_id\");",
      "CREATE INDEX \"submissions_site_created_idx\" ON \"submissions\" USING btree (\"site_id\",\"created_at\");",
      "CREATE INDEX \"urls_site_id_idx\" ON \"urls\" USING btree (\"site_id\");",
      "CREATE INDEX \"urls_site_status_idx\" ON \"urls\" USING btree (\"site_id\",\"indexing_status\");",
      "CREATE INDEX \"urls_site_checked_idx\" ON \"urls\" USING btree (\"site_id\",\"last_checked_at\");",
      "CREATE UNIQUE INDEX \"urls_site_loc_unique_idx\" ON \"urls\" USING btree (\"site_id\",\"loc\");",
      "CREATE INDEX \"users_email_idx\" ON \"users\" USING btree (\"email\");"
    ]
  },
  {
    "name": "0002_add_automation_tables.sql",
    "statements": [
      "CREATE TABLE \"site_integrations\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"site_id\" uuid NOT NULL,\n\t\"provider\" text NOT NULL,\n\t\"status\" text DEFAULT 'pending' NOT NULL,\n\t\"encrypted_secret\" text,\n\t\"public_config\" jsonb,\n\t\"automation_enabled\" boolean DEFAULT false NOT NULL,\n\t\"verified_at\" timestamp,\n\t\"last_checked_at\" timestamp,\n\t\"last_error_at\" timestamp,\n\t\"last_error_message\" text,\n\t\"created_at\" timestamp DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"site_sitemaps\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"site_id\" uuid NOT NULL,\n\t\"url\" text NOT NULL,\n\t\"is_primary\" boolean DEFAULT false NOT NULL,\n\t\"status\" text DEFAULT 'active' NOT NULL,\n\t\"last_discovered_at\" timestamp,\n\t\"last_sync_at\" timestamp,\n\t\"last_error_at\" timestamp,\n\t\"last_error_message\" text,\n\t\"created_at\" timestamp DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"submission_jobs\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"site_id\" uuid NOT NULL,\n\t\"url_id\" uuid,\n\t\"loc\" text NOT NULL,\n\t\"engine\" text NOT NULL,\n\t\"reason\" text DEFAULT 'new' NOT NULL,\n\t\"status\" text DEFAULT 'queued' NOT NULL,\n\t\"attempts\" integer DEFAULT 0 NOT NULL,\n\t\"next_run_at\" timestamp DEFAULT now() NOT NULL,\n\t\"locked_at\" timestamp,\n\t\"last_error_message\" text,\n\t\"created_at\" timestamp DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"user_integrations\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"user_id\" text NOT NULL,\n\t\"provider\" text NOT NULL,\n\t\"status\" text DEFAULT 'pending' NOT NULL,\n\t\"encrypted_secret\" text NOT NULL,\n\t\"public_config\" jsonb,\n\t\"verified_at\" timestamp,\n\t\"last_checked_at\" timestamp,\n\t\"last_error_at\" timestamp,\n\t\"last_error_message\" text,\n\t\"created_at\" timestamp DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp DEFAULT now() NOT NULL\n);",
      "ALTER TABLE \"sites\" ADD COLUMN \"indexing_host\" text;",
      "ALTER TABLE \"sites\" ADD COLUMN \"automation_enabled\" boolean DEFAULT false NOT NULL;",
      "UPDATE \"sites\" SET \"indexing_host\" = \"domain\" WHERE \"indexing_host\" IS NULL;",
      "ALTER TABLE \"submissions\" ADD COLUMN \"attempt\" integer DEFAULT 1 NOT NULL;",
      "ALTER TABLE \"urls\" ADD COLUMN \"last_seen_in_sitemap_at\" timestamp;",
      "ALTER TABLE \"urls\" ADD COLUMN \"last_submitted_at\" timestamp;",
      "ALTER TABLE \"urls\" ADD COLUMN \"last_submission_status\" text;",
      "ALTER TABLE \"site_integrations\" ADD CONSTRAINT \"site_integrations_site_id_sites_id_fk\" FOREIGN KEY (\"site_id\") REFERENCES \"public\".\"sites\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "ALTER TABLE \"site_sitemaps\" ADD CONSTRAINT \"site_sitemaps_site_id_sites_id_fk\" FOREIGN KEY (\"site_id\") REFERENCES \"public\".\"sites\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "ALTER TABLE \"submission_jobs\" ADD CONSTRAINT \"submission_jobs_site_id_sites_id_fk\" FOREIGN KEY (\"site_id\") REFERENCES \"public\".\"sites\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "ALTER TABLE \"submission_jobs\" ADD CONSTRAINT \"submission_jobs_url_id_urls_id_fk\" FOREIGN KEY (\"url_id\") REFERENCES \"public\".\"urls\"(\"id\") ON DELETE set null ON UPDATE no action;",
      "ALTER TABLE \"user_integrations\" ADD CONSTRAINT \"user_integrations_user_id_users_id_fk\" FOREIGN KEY (\"user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "CREATE INDEX \"site_integrations_site_id_idx\" ON \"site_integrations\" USING btree (\"site_id\");",
      "CREATE INDEX \"site_integrations_site_status_idx\" ON \"site_integrations\" USING btree (\"site_id\",\"status\");",
      "CREATE UNIQUE INDEX \"site_integrations_site_provider_unique_idx\" ON \"site_integrations\" USING btree (\"site_id\",\"provider\");",
      "CREATE INDEX \"site_sitemaps_site_id_idx\" ON \"site_sitemaps\" USING btree (\"site_id\");",
      "CREATE INDEX \"site_sitemaps_site_primary_idx\" ON \"site_sitemaps\" USING btree (\"site_id\",\"is_primary\");",
      "CREATE UNIQUE INDEX \"site_sitemaps_site_url_unique_idx\" ON \"site_sitemaps\" USING btree (\"site_id\",\"url\");",
      "CREATE INDEX \"submission_jobs_site_id_idx\" ON \"submission_jobs\" USING btree (\"site_id\");",
      "CREATE INDEX \"submission_jobs_status_due_idx\" ON \"submission_jobs\" USING btree (\"status\",\"next_run_at\");",
      "CREATE INDEX \"submission_jobs_engine_status_idx\" ON \"submission_jobs\" USING btree (\"engine\",\"status\");",
      "CREATE INDEX \"user_integrations_user_id_idx\" ON \"user_integrations\" USING btree (\"user_id\");",
      "CREATE INDEX \"user_integrations_user_status_idx\" ON \"user_integrations\" USING btree (\"user_id\",\"status\");",
      "CREATE UNIQUE INDEX \"user_integrations_user_provider_unique_idx\" ON \"user_integrations\" USING btree (\"user_id\",\"provider\");",
      "INSERT INTO \"site_sitemaps\" (\"site_id\", \"url\", \"is_primary\", \"status\", \"created_at\", \"updated_at\")\nSELECT \"id\", \"sitemap_url\", true, 'active', now(), now()\nFROM \"sites\"\nWHERE \"sitemap_url\" IS NOT NULL\nON CONFLICT DO NOTHING;"
    ]
  },
  {
    "name": "0003_cold_thundra.sql",
    "statements": [
      "CREATE TABLE \"api_keys\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"user_id\" text NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"key_prefix\" text NOT NULL,\n\t\"key_hash\" text NOT NULL,\n\t\"scopes\" jsonb NOT NULL,\n\t\"status\" text DEFAULT 'active' NOT NULL,\n\t\"last_used_at\" timestamp,\n\t\"expires_at\" timestamp,\n\t\"revoked_at\" timestamp,\n\t\"created_at\" timestamp DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"api_usage_events\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"api_key_id\" uuid,\n\t\"user_id\" text NOT NULL,\n\t\"method\" text NOT NULL,\n\t\"route\" text NOT NULL,\n\t\"status_code\" integer NOT NULL,\n\t\"metadata\" jsonb,\n\t\"created_at\" timestamp DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"billing_customers\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"user_id\" text NOT NULL,\n\t\"dodo_customer_id\" text NOT NULL,\n\t\"email\" text NOT NULL,\n\t\"created_at\" timestamp DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"billing_events\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"event_id\" text NOT NULL,\n\t\"event_type\" text NOT NULL,\n\t\"user_id\" text,\n\t\"payload\" jsonb NOT NULL,\n\t\"processed_at\" timestamp,\n\t\"created_at\" timestamp DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"google_integrations\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"site_id\" uuid NOT NULL,\n\t\"status\" text DEFAULT 'pending' NOT NULL,\n\t\"credentials_json\" text,\n\t\"eligible_content_types\" jsonb NOT NULL,\n\t\"public_config\" jsonb,\n\t\"verified_at\" timestamp,\n\t\"last_checked_at\" timestamp,\n\t\"last_error_at\" timestamp,\n\t\"last_error_message\" text,\n\t\"created_at\" timestamp DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"subscriptions\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"user_id\" text NOT NULL,\n\t\"dodo_subscription_id\" text NOT NULL,\n\t\"dodo_product_id\" text,\n\t\"plan\" text DEFAULT 'free' NOT NULL,\n\t\"status\" text DEFAULT 'inactive' NOT NULL,\n\t\"current_period_start\" timestamp,\n\t\"current_period_end\" timestamp,\n\t\"cancel_at_period_end\" boolean DEFAULT false NOT NULL,\n\t\"created_at\" timestamp DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp DEFAULT now() NOT NULL\n);",
      "ALTER TABLE \"api_keys\" ADD CONSTRAINT \"api_keys_user_id_users_id_fk\" FOREIGN KEY (\"user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "ALTER TABLE \"api_usage_events\" ADD CONSTRAINT \"api_usage_events_api_key_id_api_keys_id_fk\" FOREIGN KEY (\"api_key_id\") REFERENCES \"public\".\"api_keys\"(\"id\") ON DELETE set null ON UPDATE no action;",
      "ALTER TABLE \"api_usage_events\" ADD CONSTRAINT \"api_usage_events_user_id_users_id_fk\" FOREIGN KEY (\"user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "ALTER TABLE \"billing_customers\" ADD CONSTRAINT \"billing_customers_user_id_users_id_fk\" FOREIGN KEY (\"user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "ALTER TABLE \"billing_events\" ADD CONSTRAINT \"billing_events_user_id_users_id_fk\" FOREIGN KEY (\"user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE set null ON UPDATE no action;",
      "ALTER TABLE \"google_integrations\" ADD CONSTRAINT \"google_integrations_site_id_sites_id_fk\" FOREIGN KEY (\"site_id\") REFERENCES \"public\".\"sites\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "ALTER TABLE \"subscriptions\" ADD CONSTRAINT \"subscriptions_user_id_users_id_fk\" FOREIGN KEY (\"user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "CREATE INDEX \"api_keys_user_id_idx\" ON \"api_keys\" USING btree (\"user_id\");",
      "CREATE INDEX \"api_keys_status_idx\" ON \"api_keys\" USING btree (\"status\");",
      "CREATE UNIQUE INDEX \"api_keys_key_hash_unique_idx\" ON \"api_keys\" USING btree (\"key_hash\");",
      "CREATE INDEX \"api_usage_events_user_created_idx\" ON \"api_usage_events\" USING btree (\"user_id\",\"created_at\");",
      "CREATE INDEX \"api_usage_events_key_created_idx\" ON \"api_usage_events\" USING btree (\"api_key_id\",\"created_at\");",
      "CREATE UNIQUE INDEX \"billing_customers_user_unique_idx\" ON \"billing_customers\" USING btree (\"user_id\");",
      "CREATE UNIQUE INDEX \"billing_customers_dodo_customer_unique_idx\" ON \"billing_customers\" USING btree (\"dodo_customer_id\");",
      "CREATE UNIQUE INDEX \"billing_events_event_unique_idx\" ON \"billing_events\" USING btree (\"event_id\");",
      "CREATE INDEX \"billing_events_user_created_idx\" ON \"billing_events\" USING btree (\"user_id\",\"created_at\");",
      "CREATE INDEX \"google_integrations_site_id_idx\" ON \"google_integrations\" USING btree (\"site_id\");",
      "CREATE INDEX \"google_integrations_status_idx\" ON \"google_integrations\" USING btree (\"status\");",
      "CREATE UNIQUE INDEX \"google_integrations_site_unique_idx\" ON \"google_integrations\" USING btree (\"site_id\");",
      "CREATE INDEX \"subscriptions_user_id_idx\" ON \"subscriptions\" USING btree (\"user_id\");",
      "CREATE INDEX \"subscriptions_status_idx\" ON \"subscriptions\" USING btree (\"status\");",
      "CREATE UNIQUE INDEX \"subscriptions_dodo_subscription_unique_idx\" ON \"subscriptions\" USING btree (\"dodo_subscription_id\");"
    ]
  }
];
