export type DirectoryPriority = "P0" | "P1" | "P2" | "P3";
export type DirectoryCost = "free" | "freemium" | "paid";

export type SubmissionDirectory = {
	name: string;
	url: string;
	category: string;
	priority: DirectoryPriority;
	cost: DirectoryCost;
	reviewRequired: boolean;
	bestFor: string;
	submissionNotes: string;
	expectedEffort: "low" | "medium" | "high";
	score: number;
};

function directory(
	name: string,
	url: string,
	category: string,
	priority: DirectoryPriority,
	cost: DirectoryCost,
	reviewRequired: boolean,
	bestFor: string,
	submissionNotes: string,
	expectedEffort: "low" | "medium" | "high",
	score: number,
): SubmissionDirectory {
	return { name, url, category, priority, cost, reviewRequired, bestFor, submissionNotes, expectedEffort, score };
}

export const submissionDirectories = [
	directory("Product Hunt", "https://www.producthunt.com/", "launch", "P0", "free", true, "Public product launches", "Prepare maker comment, launch assets, and early user asks before launch day.", "high", 98),
	directory("G2", "https://www.g2.com/products/new", "reviews", "P0", "freemium", true, "B2B SaaS credibility", "Create product profile and start collecting real customer reviews.", "high", 96),
	directory("Capterra", "https://www.capterra.com/vendors/sign-up", "reviews", "P0", "freemium", true, "Business software buyers", "Submit through Gartner Digital Markets and keep category copy clear.", "high", 95),
	directory("Crunchbase", "https://www.crunchbase.com/", "startup", "P0", "freemium", true, "Investor and partner discovery", "Add company, founder, funding, product, and website details.", "medium", 94),
	directory("Wellfound", "https://wellfound.com/", "startup", "P0", "free", true, "Hiring, fundraising, startup profile", "Create a complete company profile before using it for hiring.", "medium", 93),
	directory("AlternativeTo", "https://alternativeto.net/", "software", "P0", "free", true, "Alternative pages and comparison SEO", "Submit as an alternative to adjacent SEO, indexing, and analytics tools.", "medium", 92),
	directory("GitHub", "https://github.com/", "developer", "P0", "free", false, "Open-source CLI, docs, and install scripts", "Publish CLI, skill, and examples in a public repo with strong README.", "medium", 91),
	directory("LinkedIn Product Pages", "https://www.linkedin.com/products/", "business", "P0", "free", true, "Professional buyer visibility", "Use concise B2B product positioning and connect the company page.", "medium", 90),
	directory("SaaSHub", "https://www.saashub.com/", "software", "P0", "free", true, "SaaS alternatives and reviews", "Add competitors and categories carefully to earn comparison traffic.", "medium", 89),
	directory("SourceForge", "https://sourceforge.net/", "developer", "P0", "free", true, "Open-source projects and developer tools", "Best for CLI, MCP server, and open templates rather than pure SaaS pages.", "medium", 88),
	directory("TrustRadius", "https://www.trustradius.com/vendor", "reviews", "P1", "freemium", true, "B2B review discovery", "Prioritize after first paying customers can leave reviews.", "high", 87),
	directory("Software Advice", "https://www.softwareadvice.com/vendors/", "reviews", "P1", "freemium", true, "Software buyer lead flow", "Use the same Gartner profile data as Capterra where possible.", "high", 86),
	directory("GetApp", "https://www.getapp.com/vendors/", "reviews", "P1", "freemium", true, "SaaS category discovery", "Usually covered through Gartner Digital Markets submission.", "high", 85),
	directory("AppSumo", "https://appsumo.com/sell/", "deals", "P1", "paid", true, "Lifetime deal distribution", "Use only after activation and support workflows are mature.", "high", 84),
	directory("Uneed", "https://www.uneed.best/", "launch", "P1", "free", true, "Curated tools and indie launches", "Submit clear screenshots and a short founder-friendly value prop.", "medium", 83),
	directory("DevHunt", "https://devhunt.org/", "developer", "P1", "free", true, "Developer tools", "Frame IndexFast as CLI, MCP, and agent-ready indexing infrastructure.", "medium", 82),
	directory("BetaList", "https://betalist.com/", "startup", "P1", "freemium", true, "Pre-launch and beta users", "Use if launching a waitlist, beta, or agent-first workflow preview.", "medium", 82),
	directory("Indie Hackers Products", "https://www.indiehackers.com/products", "community", "P1", "free", true, "Indie founder traffic", "Share real metrics and build-in-public updates, not just a listing.", "medium", 81),
	directory("Hacker News Show HN", "https://news.ycombinator.com/show", "community", "P1", "free", true, "Technical audience feedback", "Launch with a working demo, honest positioning, and no hype.", "high", 81),
	directory("There's An AI For That", "https://theresanaiforthat.com/", "ai", "P1", "freemium", true, "AI tool discovery", "Submit agent, MCP, AI visibility, and AI crawler features.", "medium", 80),
	directory("Toolify", "https://www.toolify.ai/", "ai", "P1", "freemium", true, "AI tools directory", "Use AI-agent integration and MCP setup copy in the listing.", "medium", 79),
	directory("Futurepedia", "https://www.futurepedia.io/", "ai", "P1", "freemium", true, "AI product discovery", "Position around AI search visibility and AI IDE workflows.", "medium", 78),
	directory("FutureTools", "https://www.futuretools.io/", "ai", "P1", "free", true, "AI builders", "Highlight MCP, CLI, llms.txt, and AI crawler readiness.", "medium", 77),
	directory("AI Tools Directory", "https://aitoolsdirectory.com/", "ai", "P1", "free", true, "General AI tools", "Submit after the AI/MCP landing page section is live.", "low", 76),
	directory("Insidr AI Tools", "https://www.insidr.ai/ai-tools/", "ai", "P1", "free", true, "AI tools catalog", "Best once a public MCP page and screenshots exist.", "low", 75),
	directory("OpenTools", "https://opentools.ai/", "ai", "P1", "free", true, "AI tool discovery", "Focus on agent-ready SEO operations.", "low", 75),
	directory("TopAI.tools", "https://topai.tools/", "ai", "P1", "freemium", true, "AI software discovery", "Add clear category tags and pricing.", "low", 74),
	directory("Microlaunch", "https://microlaunch.net/", "launch", "P1", "free", true, "Micro-SaaS launch", "Use for the agent-first v1 launch milestone.", "medium", 74),
	directory("Peerlist", "https://peerlist.io/projects", "community", "P1", "free", true, "Builder community", "Submit as a project and ask for product feedback.", "medium", 73),
	directory("StartupBase", "https://startupbase.io/", "startup", "P1", "free", true, "Startup directory", "Strong concise description and founder story matter.", "low", 72),
	directory("Launched", "https://launched.io/", "launch", "P2", "free", true, "New product launches", "Use a launch-focused screenshot and short category tags.", "low", 71),
	directory("Launching Next", "https://www.launchingnext.com/", "startup", "P2", "freemium", true, "Early startup discovery", "Good for pre-YC traction links.", "low", 70),
	directory("KillerStartups", "https://www.killerstartups.com/", "startup", "P2", "free", true, "Startup discovery", "Use only after landing page copy is polished.", "low", 69),
	directory("Startup Stash", "https://startupstash.com/", "startup", "P2", "free", true, "Startup resource discovery", "Submit if tool category fit is available.", "medium", 69),
	directory("Startup Buffer", "https://startupbuffer.com/", "startup", "P2", "freemium", true, "Startup launch listing", "Prepare concise founder-facing benefits.", "low", 68),
	directory("StartupBlink", "https://www.startupblink.com/", "startup", "P2", "freemium", true, "Startup ecosystem discovery", "Add location and company metadata.", "medium", 68),
	directory("F6S", "https://www.f6s.com/", "startup", "P2", "free", true, "Startup programs and founder visibility", "Useful for accelerator and grant discovery.", "medium", 67),
	directory("Angel Investment Network", "https://www.angelinvestmentnetwork.com/", "startup", "P2", "freemium", true, "Investor visibility", "Use if actively fundraising.", "high", 67),
	directory("EU-Startups Directory", "https://www.eu-startups.com/", "startup", "P2", "paid", true, "European startup visibility", "Only if region and audience fit.", "medium", 66),
	directory("Fazier", "https://fazier.com/", "launch", "P2", "free", true, "Indie launches", "Works well for small product updates.", "low", 66),
	directory("Tiny Startups", "https://tinystartups.com/", "startup", "P2", "free", true, "Micro-SaaS buyers", "Use concise metrics and screenshots.", "low", 65),
	directory("SideProjectors", "https://www.sideprojectors.com/", "startup", "P2", "free", true, "Side projects and acquisitions", "Useful if offering templates, CLI, or open assets.", "low", 65),
	directory("Acquire.com", "https://acquire.com/", "marketplace", "P3", "paid", true, "Acquisition readiness", "Not a launch channel; use only for sale exploration.", "high", 55),
	directory("Flippa", "https://flippa.com/", "marketplace", "P3", "paid", true, "Website marketplace visibility", "Not priority unless selling a site or template.", "high", 54),
	directory("SaaS Worthy", "https://www.saasworthy.com/", "software", "P2", "free", true, "SaaS product comparison", "Submit with competitor alternatives and pricing.", "medium", 64),
	directory("Crozdesk", "https://crozdesk.com/", "software", "P2", "freemium", true, "Business software comparison", "Use detailed feature copy and category mapping.", "medium", 64),
	directory("FinancesOnline", "https://financesonline.com/", "reviews", "P2", "freemium", true, "B2B reviews", "Prioritize once customers can provide social proof.", "high", 63),
	directory("Serchen", "https://www.serchen.com/", "software", "P2", "free", true, "Cloud services directory", "Good fit for SaaS/platform categories.", "medium", 63),
	directory("Slashdot Business Software", "https://slashdot.org/software/", "software", "P2", "free", true, "Software alternatives", "Use if category exists for SEO, monitoring, or analytics.", "medium", 62),
	directory("StackShare", "https://stackshare.io/", "developer", "P2", "free", true, "Developer stack discovery", "Add CLI/API/MCP stack profile and integrations.", "medium", 62),
	directory("RapidAPI Hub", "https://rapidapi.com/hub", "api", "P2", "freemium", true, "API discovery", "Only if publishing public API endpoints through RapidAPI.", "high", 61),
	directory("Postman Public API Network", "https://www.postman.com/explore", "api", "P2", "free", true, "API docs and developers", "Publish a collection for IndexFast REST endpoints.", "medium", 61),
	directory("APILayer Marketplace", "https://apilayer.com/", "api", "P3", "paid", true, "API marketplace", "Later-stage API distribution.", "high", 52),
	directory("ProgrammableWeb Archive Alternatives", "https://www.programmableweb.com/", "api", "P3", "free", true, "API discovery research", "Use as research reference; verify current submission availability.", "medium", 50),
	directory("Dev.to", "https://dev.to/", "community", "P2", "free", false, "Developer education", "Publish how-to posts for MCP, CLI, and indexing automation.", "medium", 60),
	directory("Hashnode", "https://hashnode.com/", "community", "P2", "free", false, "Developer blogs", "Republish technical setup guides with canonicals.", "medium", 60),
	directory("Medium", "https://medium.com/", "content", "P3", "free", false, "Founder stories and guides", "Use canonical links back to IndexFast resources.", "low", 51),
	directory("Reddit r/SaaS", "https://www.reddit.com/r/SaaS/", "community", "P2", "free", true, "SaaS founder feedback", "Share useful resources, not just promotion.", "medium", 59),
	directory("Reddit r/SideProject", "https://www.reddit.com/r/SideProject/", "community", "P2", "free", true, "Indie builders", "Launch with demo and free tool links.", "medium", 58),
	directory("Reddit r/SEO", "https://www.reddit.com/r/SEO/", "community", "P2", "free", true, "SEO operator feedback", "Use educational posts and avoid sales-only submissions.", "medium", 58),
	directory("Reddit r/bigseo", "https://www.reddit.com/r/bigseo/", "community", "P2", "free", true, "Technical SEO audience", "Share research and tooling details.", "medium", 57),
	directory("Reddit r/webdev", "https://www.reddit.com/r/webdev/", "community", "P3", "free", true, "Developer visibility", "Only post technical angle like MCP or CLI.", "medium", 50),
	directory("Quora", "https://www.quora.com/", "content", "P3", "free", true, "Answer-driven discovery", "Answer indexing and pSEO questions with useful context.", "medium", 49),
	directory("Stack Overflow", "https://stackoverflow.com/", "developer", "P3", "free", true, "Technical Q&A", "Do not self-promote; answer real technical questions only.", "medium", 48),
	directory("Google Business Profile", "https://www.google.com/business/", "local", "P2", "free", true, "Local/service credibility", "Useful if selling agency services or consulting around IndexFast.", "medium", 57),
	directory("Bing Places", "https://www.bingplaces.com/", "local", "P2", "free", true, "Local Bing visibility", "Useful for agency/service entity discovery.", "medium", 56),
	directory("Yelp for Business", "https://business.yelp.com/", "local", "P3", "free", true, "Local services", "Only if offering local SEO services.", "high", 45),
	directory("Clutch", "https://clutch.co/", "agency", "P2", "freemium", true, "Agency/service credibility", "Best if IndexFast offers agency services or implementation help.", "high", 56),
	directory("DesignRush", "https://www.designrush.com/", "agency", "P3", "paid", true, "Agency listing", "Use only if selling done-for-you SEO services.", "high", 44),
	directory("GoodFirms", "https://www.goodfirms.co/", "agency", "P2", "freemium", true, "Software/service reviews", "Useful for software and agency hybrid positioning.", "high", 55),
	directory("UpCity", "https://upcity.com/", "agency", "P3", "freemium", true, "Agency discovery", "Only if services arm exists.", "high", 43),
	directory("Sortlist", "https://www.sortlist.com/", "agency", "P3", "freemium", true, "Agency discovery", "Lower priority for pure SaaS.", "high", 42),
	directory("Airtable Universe", "https://www.airtable.com/universe", "templates", "P3", "free", true, "Template discovery", "Publish directory tracking templates if available.", "medium", 48),
	directory("Notion Template Gallery", "https://www.notion.com/templates", "templates", "P2", "free", true, "SEO checklist templates", "Ship a free IndexFast launch checklist template.", "medium", 55),
	directory("Gumroad Discover", "https://gumroad.com/discover", "marketplace", "P3", "free", true, "Digital templates", "Use for paid checklists or launch templates.", "medium", 47),
	directory("Lemon Squeezy Discover", "https://www.lemonsqueezy.com/", "marketplace", "P3", "paid", true, "Digital product sales", "Lower priority because billing uses DodoPayments.", "medium", 44),
	directory("Ko-fi Shop", "https://ko-fi.com/", "marketplace", "P3", "free", true, "Digital resources", "Use only for auxiliary templates.", "low", 41),
	directory("Chrome Web Store", "https://chromewebstore.google.com/", "extension", "P2", "free", true, "Browser extension visibility", "Submit only after Chrome extension exists.", "high", 56),
	directory("WordPress Plugin Directory", "https://wordpress.org/plugins/developers/add/", "wordpress", "P2", "free", true, "WordPress integrations", "Submit only after plugin exists.", "high", 56),
	directory("Shopify App Store", "https://apps.shopify.com/", "ecommerce", "P3", "paid", true, "Shopify merchant distribution", "Future ecommerce integration channel.", "high", 46),
	directory("Webflow Marketplace", "https://webflow.com/marketplace", "websites", "P3", "free", true, "Webflow templates/apps", "Future no-code integration channel.", "high", 43),
	directory("Framer Marketplace", "https://www.framer.com/marketplace/", "websites", "P3", "free", true, "Website templates", "Use if shipping SEO audit widgets/templates.", "medium", 42),
	directory("Vercel Marketplace", "https://vercel.com/marketplace", "developer", "P3", "free", true, "Developer integrations", "Future integration listing if API app exists.", "high", 45),
	directory("Cloudflare Marketplace", "https://www.cloudflare.com/apps/", "developer", "P3", "free", true, "Cloudflare users", "Future Worker/app distribution surface.", "high", 45),
	directory("Zapier App Directory", "https://zapier.com/apps", "automation", "P2", "free", true, "Workflow automation buyers", "Create only after Zapier integration exists.", "high", 55),
	directory("Make App Directory", "https://www.make.com/en/integrations", "automation", "P3", "free", true, "Automation builders", "Future integration listing.", "high", 45),
	directory("n8n Integrations", "https://n8n.io/integrations/", "automation", "P3", "free", true, "Open automation users", "Future community node listing.", "high", 44),
	directory("Pipedream Apps", "https://pipedream.com/apps", "automation", "P3", "free", true, "Developer automation", "Future API integration listing.", "medium", 44),
	directory("MCP Registry", "https://modelcontextprotocol.io/registry", "agent", "P1", "free", true, "Remote MCP server discovery", "Publish after authenticated MCP endpoint and server metadata are stable.", "medium", 74),
	directory("Smithery", "https://smithery.ai/", "agent", "P1", "free", true, "MCP server discovery", "List IndexFast MCP server when tool schemas are stable.", "medium", 73),
	directory("Composio", "https://composio.dev/", "agent", "P2", "free", true, "Agent tool integrations", "Explore marketplace/API integration path.", "medium", 58),
	directory("LangChain Integrations", "https://www.langchain.com/", "agent", "P3", "free", true, "AI framework ecosystem", "Future loader/tool integration.", "high", 45),
	directory("LlamaIndex Integrations", "https://www.llamaindex.ai/", "agent", "P3", "free", true, "AI data integrations", "Future resources connector.", "high", 44),
	directory("Cursor Directory", "https://cursor.directory/", "agent", "P2", "free", true, "AI IDE users", "Submit CLI, MCP config, and prompt snippets if accepted.", "medium", 57),
	directory("Awesome MCP Servers", "https://github.com/punkpeye/awesome-mcp-servers", "agent", "P1", "free", true, "MCP GitHub discovery", "Open a PR once the MCP server is production-ready.", "medium", 72),
	directory("Awesome AI Tools", "https://github.com/mahseema/awesome-ai-tools", "ai", "P3", "free", true, "GitHub AI lists", "Submit only to active maintained lists.", "medium", 43),
	directory("Awesome SEO", "https://github.com/marcobiedermann/search-engine-optimization", "seo", "P3", "free", true, "SEO GitHub discovery", "Submit free tools if repo accepts additions.", "medium", 43),
	directory("Moz Community", "https://moz.com/community", "seo", "P3", "free", true, "SEO community", "Educational participation only.", "medium", 42),
	directory("Ahrefs Webmaster Tools", "https://ahrefs.com/webmaster-tools", "seo", "P3", "free", false, "Backlink/site audit reference", "Not a submission directory; include as resource, not launch channel.", "low", 40),
	directory("Semrush App Center", "https://www.semrush.com/apps/", "seo", "P3", "paid", true, "SEO ecosystem apps", "Future integration app listing.", "high", 42),
	directory("SEO Review Tools", "https://www.seoreviewtools.com/", "seo", "P3", "free", true, "SEO tool discovery", "Potential free tool backlink/resource placement.", "medium", 41),
	directory("Serpstat Marketplace", "https://serpstat.com/", "seo", "P3", "paid", true, "SEO ecosystem", "Research current partner/app options first.", "high", 40),
	directory("BuiltWith", "https://builtwith.com/", "software", "P3", "freemium", false, "Technology profile visibility", "IndexFast may appear naturally after adoption.", "low", 39),
	directory("Wappalyzer", "https://www.wappalyzer.com/", "software", "P3", "freemium", true, "Technology discovery", "Future technology profile if widget/script exists.", "medium", 39),
	directory("Trustpilot", "https://www.trustpilot.com/business", "reviews", "P2", "freemium", true, "Public reviews", "Use once support and review request workflow are ready.", "high", 54),
	directory("Crozdesk Vendor", "https://crozdesk.com/vendors", "reviews", "P2", "freemium", true, "SaaS reviews", "Duplicate-safe with Crozdesk product listing.", "medium", 53),
	directory("PeerSpot", "https://www.peerspot.com/vendors", "reviews", "P3", "freemium", true, "Enterprise reviews", "Later-stage enterprise credibility.", "high", 41),
	directory("SourceForge Business Software", "https://sourceforge.net/software/vendors/new", "software", "P2", "free", true, "Software comparison", "Use SaaS listing path alongside open-source project if available.", "medium", 53),
	directory("Capterra Shortlist", "https://www.capterra.com/shortlist/", "reviews", "P3", "freemium", true, "Category awards", "Outcome of review traction, not first submission.", "high", 38),
	directory("TrustRadius Buyer Blog", "https://www.trustradius.com/buyer-blog", "content", "P3", "freemium", true, "B2B content visibility", "Pitch educational content after product listing.", "high", 38),
	directory("BetaPage", "https://betapage.co/", "startup", "P2", "free", true, "Startup beta discovery", "Good low-effort beta listing.", "low", 52),
	directory("All Startups", "https://www.allstartups.info/", "startup", "P2", "free", true, "Startup directory", "Verify submission availability before spending time.", "low", 51),
	directory("Startup Ranking", "https://www.startupranking.com/", "startup", "P2", "free", true, "Startup profile", "Add company metadata and social links.", "low", 51),
	directory("GrowthHackers", "https://growthhackers.com/", "community", "P3", "free", true, "Growth community", "Share resource hub or directory research, not product-only posts.", "medium", 40),
	directory("Designer News", "https://www.designernews.co/", "community", "P3", "free", true, "Design/product audience", "Only if UI/product design story is strong.", "medium", 37),
	directory("Lobsters", "https://lobste.rs/", "community", "P3", "free", true, "Technical community", "Only submit deeply technical MCP/CLI posts.", "medium", 37),
	directory("Awesome Indie", "https://github.com/mezod/awesome-indie", "community", "P3", "free", true, "Indie GitHub list", "Submit if criteria match.", "medium", 37),
	directory("OpenAlternative", "https://openalternative.co/", "open-source", "P2", "free", true, "Open-source alternatives", "Use if CLI/MCP server is published open-source.", "medium", 52),
	directory("LibHunt", "https://www.libhunt.com/", "open-source", "P2", "free", true, "Open-source project discovery", "Best for CLI package and SDK.", "medium", 52),
	directory("npm", "https://www.npmjs.com/", "developer", "P1", "free", false, "CLI/package distribution", "Publish `indexfast` CLI package with useful keywords.", "medium", 73),
	directory("Homebrew", "https://brew.sh/", "developer", "P2", "free", true, "CLI installation", "Submit formula after CLI package is stable.", "high", 56),
	directory("Docker Hub", "https://hub.docker.com/", "developer", "P3", "free", false, "Self-hosted MCP/API examples", "Use if shipping a containerized local MCP proxy.", "medium", 42),
	directory("GitLab Explore", "https://gitlab.com/explore", "developer", "P3", "free", false, "Open-source mirror", "Optional mirror if GitHub repo is primary.", "low", 35),
	directory("Codeberg", "https://codeberg.org/", "developer", "P3", "free", false, "Open-source mirror", "Optional mirror for open assets.", "low", 34),
	directory("Tally Template Gallery", "https://tally.so/templates", "templates", "P3", "free", true, "Forms/templates", "Publish an SEO intake form template if useful.", "medium", 36),
	directory("Typeform Templates", "https://www.typeform.com/templates/", "templates", "P3", "free", true, "Forms/templates", "Use if creating customer SEO audit intake templates.", "medium", 35),
	directory("AIPRM", "https://www.aiprm.com/", "ai", "P3", "freemium", true, "Prompt distribution", "Potential prompt pack for indexing audits.", "medium", 36),
	directory("PromptBase", "https://promptbase.com/", "ai", "P3", "paid", true, "Prompt products", "Low priority unless selling prompt packs.", "medium", 34),
	directory("Kaggle Datasets", "https://www.kaggle.com/datasets", "data", "P3", "free", true, "Public dataset visibility", "Only if publishing anonymized SEO directory/resource dataset.", "medium", 34),
	directory("DataHub", "https://datahub.io/", "data", "P3", "free", true, "Open data discovery", "Optional for public resource catalog exports.", "medium", 33),
	directory("Awesome Lists", "https://github.com/sindresorhus/awesome", "open-source", "P3", "free", true, "GitHub awesome ecosystem", "Submit to specific maintained lists, not the root repo.", "medium", 33),
	directory("BetaBound", "https://www.betabound.com/", "startup", "P3", "free", true, "Beta testing", "Use if seeking testers for MCP/CLI workflows.", "medium", 36),
	directory("User Interviews", "https://www.userinterviews.com/", "research", "P3", "paid", true, "Customer research", "Not a directory; use for paid user interviews.", "high", 32),
	directory("Respondent", "https://www.respondent.io/", "research", "P3", "paid", true, "Customer research", "Recruit SEO operators for interviews.", "high", 32),
	directory("Y Combinator Startup Directory", "https://www.ycombinator.com/companies", "startup", "P3", "free", true, "YC company visibility", "Only available after acceptance; track as aspirational.", "low", 30),
] satisfies SubmissionDirectory[];

export function getDirectoriesByPriority(priority?: DirectoryPriority) {
	const rows = priority ? submissionDirectories.filter((item) => item.priority === priority) : submissionDirectories;
	return [...rows].sort((a, b) => b.score - a.score || a.name.localeCompare(b.name));
}

export function getDirectoryStats() {
	return {
		total: submissionDirectories.length,
		p0: submissionDirectories.filter((item) => item.priority === "P0").length,
		p1: submissionDirectories.filter((item) => item.priority === "P1").length,
		free: submissionDirectories.filter((item) => item.cost === "free").length,
	};
}
